-- Seed vagas (job opportunities)
INSERT INTO public.vagas (titulo, empresa, descricao, tipo, localizacao, requisitos, beneficios, salario, link_candidatura) VALUES
('Estágio em Desenvolvimento Web', 'Tech Solutions Ltda', 'Oportunidade para estudantes de tecnologia desenvolverem habilidades em desenvolvimento web com tecnologias modernas.', 'estagio', 'Itabuna, BA', 'Cursando superior em Ciência da Computação, Sistemas de Informação ou áreas relacionadas. Conhecimento básico em HTML, CSS e JavaScript.', 'Vale-transporte, Vale-refeição, Ambiente colaborativo', 'R$ 800,00', 'https://exemplo.com/vaga1'),
('Jovem Aprendiz - Administrativo', 'Comércio Bahia S.A', 'Programa de aprendizagem para jovens interessados em atuar na área administrativa.', 'jovem-aprendiz', 'Itabuna, BA', 'Ensino médio completo ou cursando. Idade entre 14 e 24 anos.', 'Vale-transporte, Vale-alimentação, Curso profissionalizante', 'R$ 600,00', 'https://exemplo.com/vaga2'),
('Primeiro Emprego - Atendimento ao Cliente', 'Supermercado Central', 'Vaga para atendimento ao cliente em supermercado. Primeira oportunidade no mercado de trabalho.', 'primeiro-emprego', 'Itabuna, BA', 'Ensino médio completo. Boa comunicação e disposição para aprender.', 'Vale-transporte, Vale-refeição', 'R$ 1.320,00', 'https://exemplo.com/vaga3'),
('Estágio em Marketing Digital', 'Agência Criativa Digital', 'Estágio para estudantes interessados em marketing digital e gestão de redes sociais.', 'estagio', 'Itabuna, BA', 'Cursando superior em Marketing, Publicidade ou áreas relacionadas. Conhecimento em redes sociais.', 'Vale-transporte, Ambiente criativo', 'R$ 700,00', 'https://exemplo.com/vaga4');

-- Seed cursos (courses)
INSERT INTO public.cursos (titulo, descricao, plataforma, categoria, duracao, nivel, link) VALUES
('Introdução à Informática', 'Curso completo de informática básica, incluindo Windows, Word, Excel e Internet.', 'Fundação Bradesco', 'Informática', '40 horas', 'iniciante', 'https://www.ev.org.br/cursos/introducao-a-informatica'),
('Inglês Básico Online', 'Aprenda inglês do zero com aulas interativas e exercícios práticos.', 'Duolingo', 'Idiomas', 'Flexível', 'iniciante', 'https://www.duolingo.com/course/en/pt/Learn-English'),
('Marketing Digital para Iniciantes', 'Fundamentos de marketing digital, SEO, redes sociais e estratégias online.', 'Google Ateliê Digital', 'Marketing', '40 horas', 'iniciante', 'https://ateliedigital.withgoogle.com/'),
('Atendimento ao Cliente', 'Técnicas e boas práticas para excelência no atendimento ao cliente.', 'SEBRAE', 'Atendimento', '20 horas', 'iniciante', 'https://www.sebrae.com.br/sites/PortalSebrae/cursosonline');

-- Seed dicas (tips)
INSERT INTO public.dicas (titulo, descricao, conteudo, categoria) VALUES
('Como Fazer um Currículo Profissional', 'Aprenda a criar um currículo que chama atenção dos recrutadores.', 'Um bom currículo deve ser claro, objetivo e destacar suas principais qualificações. Inclua: dados pessoais, objetivo profissional, formação acadêmica, experiências (mesmo que voluntárias), cursos e habilidades. Mantenha o formato limpo e use no máximo 2 páginas. Revise sempre para evitar erros de português.', 'curriculo'),
('Dicas para Entrevista de Emprego', 'Prepare-se para sua primeira entrevista com estas dicas essenciais.', 'Antes da entrevista: pesquise sobre a empresa, prepare respostas para perguntas comuns, escolha uma roupa adequada. Durante: seja pontual, cumprimente com firmeza, mantenha contato visual, seja honesto e mostre interesse. Depois: agradeça a oportunidade e aguarde o retorno no prazo informado.', 'entrevista'),
('Como Usar o LinkedIn para Conseguir Emprego', 'O LinkedIn é uma ferramenta poderosa para sua carreira profissional.', 'Crie um perfil completo com foto profissional, título atraente e resumo que destaque suas habilidades. Conecte-se com profissionais da sua área, participe de grupos, compartilhe conteúdo relevante e interaja com publicações. Use a busca de vagas e ative o modo "Disponível para oportunidades".', 'linkedin'),
('Canva: Ferramenta Gratuita para Criar Currículos', 'Use o Canva para criar currículos visuais e profissionais gratuitamente.', 'O Canva oferece templates gratuitos de currículos profissionais. Acesse canva.com, crie uma conta gratuita, busque por "currículo" e escolha um modelo. Personalize com suas informações, cores e fontes. Baixe em PDF e use em suas candidaturas. É fácil, rápido e o resultado é profissional.', 'canva');
